language: cpp
compiler:
  - gcc
install:
  - sudo apt-get install freeglut3-dev libxi-dev libxmu-dev libcurl4-gnutls-dev libdap-dev libgdal1-dev liblapack-dev liblas-dev
  - cmake . && make
script: ctest

